# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: lyj's blog
subtitle:
description:
keywords: Technology,Skill,Program,Coding,Javascript,Node.js,Docker,Kubernetes
author: lyj
language: zh
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: /
root: /
# permalink: :year/:month/:day/:title/
permalink: posts/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit:
  content_limit_delim: ' '

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:liuyanjie/liuyanjie.github.io.git
  branch: master
  # message: [message]

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: jacman
stylus:
  compress: true

theme_config:
  ##### Menu
  menu:
    Home: /
    Archives: /archives
    # About: /about
  ## you can create `tags` and `categories` folders in `../source`.
  ## And create a `index.md` file in each of them.
  ## set `front-matter`as
  ## layout: tags (or categories)
  ## title: tags (or categories)
  ## ---
  
  #### Widgets
  widgets: 
  # - github-card
  - category
  - tag
  - links
  - rss
  - tagcloud
  ## provide eight widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo
  
  #### RSS 
  rss: /atom.xml ## RSS address.
  
  #### Image
  imglogo:
    enable: true               ## display image logo true/false.
    src: img/jacman.png         ## `.svg` and `.png` are recommended, please put image into the theme folder `/jacman/source/img`.
  favicon: img/avatar.png       ## size:32px*32px,`.ico` is recommended, please put image into the theme folder `/jacman/source/img`.     
  apple_icon: img/jacman.jpg    ## size:114px*114px, please put image into the theme folder `/jacman/source/img`.
  author_img:     ## size:220px*220px. display author avatar picture.if don't want to display,please don't set this.
  banner_img: img/banner.jpg    ## size:1920px*200px+. Banner Picture
  
  ### Theme Color 
  theme_color:
    # theme: '#5ca6cb'    ##the defaut theme color is blue
  
  # 代码高亮主题
  # available: default | night
  highlight_theme: default
  
  #### index post is expanding or not 
  index:
    expand: false           ## default is unexpanding,so you can only see the short description of each post.
    excerpt_link: Read More  
  
  close_aside: true  #close sidebar in post page if true
  mathjax: true      #enable mathjax if true
  
  ### Creative Commons License Support, see http://creativecommons.org/ 
  ### you can choose: by , by-nc , by-nc-nd , by-nc-sa , by-nd , by-sa , zero
  creative_commons: by-nc
  
  #### Author information
  author:
    intro_line1:  "Not every technical problems should be resolved through technical means." ## your introduction on the bottom of the page
    intro_line2:  "Fighting"       ## the 2nd line
    # weibo: 2176287895                   ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
    # weibo_verifier: b3593ceb            ## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.
    tsina:                                ## e.g. 2176287895  Your weibo ID,It will be used in share button.
    douban:                               ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
    # zhihu: ryxc-liu-yan-jie               ## e.g. jark  for http://www.zhihu.com/people/jark
    email: liuyj619@gmail.com             ## e.g. imjark@gmail.com
    # twitter: ryxcxyr                      ## e.g. jarkwu for https://twitter.com/jarkwu
    github: liuyanjie                     ## e.g. wuchong for https://github.com/wuchong
    facebook:                             ## e.g. imjark for https://facebook.com/imjark
    # linkedin: liuyj619                    ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
    google_plus: "101963751496807079381"  ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
    stackoverflow: 5954388                ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
  ## if you set them, the corresponding share button will show on the footer
  
  #### Toc
  toc:
    article: true   ## show contents in article.
    aside: true     ## show contents in aside.
  ## you can set both of the value to true of neither of them.
  ## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.
  
  #### Links
  links:
    # 码农圈: https://coderq.com,一个面向程序员交流分享的新一代社区
    # Jark's Blog: http://wuchong.me
    须臾之学: https://blog.xizhibei.me
  
  #### Comment
  duoshuo_shortname:    ## e.g. wuchong   your duoshuo short name.
  disqus_shortname: liuyanjie    ## e.g. wuchong   your disqus short name.
  gentie_key:           ## your 163 gentie key, see https://gentie.163.com/
  changyan_appid:       ## changyan app id, see http://changyan.kuaizhan.com/
  changyan_appkey:      ## changyan app key, see http://changyan.kuaizhan.com/
  
  #### Share button
  jiathis:
    enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
    id:    ## e.g. 1889330 your jiathis ID. 
    tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.
  
  #### Analytics
  google_analytics:
    enable: true
    id: UA-131498998-1       ## e.g. UA-46321946-2 your google analytics ID.
    site:      ## e.g. wuchong.me your google analytics site or set the value as auto.
  baidu_tongji:
    enable: true
    sitecode: 4cd57e104d0d9f5862dd91d0acdb9eee ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
  cnzz_tongji:
    enable: false
    siteid:    ## e.g. 1253575964 your cnzz tongji site id
  
  #### Miscellaneous
  ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
  fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
  totop: true           ## if you want to scroll to top in every post set the value to true

  #### Custom Search
  google_cse: 
    enable: true
    cx: 014348069229275019795:-z92dm0sjiy  ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
  ## https://www.google.com/cse/ 
  ## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
  ## set the 'front-matter' as
  ## layout: search 
  ## title: search
  ## ---
  
  baidu_search:     ## http://zn.baidu.com/
    enable: false
    id:   ## e.g. "783281470518440642"  for your baidu search id
    site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site
  
  tinysou_search:     ## http://tinysou.com/
    enable: false
    id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
  
