# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: liuyanjie's blog
subtitle: 
description: KISS DRY
keywords: 个人博客,技术分享,前端,后端,容器,架构
author: liuyanjie
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.butonly.com/
root: /
# permalink: :year/:month/:day/:title/
permalink: posts/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link.enable: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit:
  content_limit_delim: ' '

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  # repo: git@github.com:butonly/butonly.github.io.git
  repo: https://github.com/butonly/butonly.github.io.git
  branch: master
  token: $GITHUB_TOKEN
  # message: [message]

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
stylus:
  compress: true

# $ export HEXO_ALGOLIA_INDEXING_KEY=459ace1d7f5aabfa15b4f89baba340b3 # Use Git Bash
# $ hexo clean
# $ hexo algolia
algolia:
  applicationID: FRAAR0AUP0
  apiKey: 459ace1d7f5aabfa15b4f89baba340b3
  indexName: blog.butonly.com
  chunkSize: 5000

theme_config:
  # ---------------------------------------------------------------
  # Theme Core Configuration Settings
  # See: https://theme-next.js.org/docs/theme-settings/
  # ---------------------------------------------------------------
  minify: true
  scheme: Gemini
  darkmode: true

  # ---------------------------------------------------------------
  # Site Information Settings
  # ---------------------------------------------------------------
  favicon:
    small: /favicon.png
    medium: /favicon.png
    apple_touch_icon: /favicon.png
    safari_pinned_tab: /favicon.png
    android_manifest: /manifest.json
    ms_browserconfig: /browserconfig.xml
  custom_logo: logo.png
  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: true

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------
  menu:
    home: / || home
    archives: /archives/ || archive
    categories: /categories/ || th
    tags: /tags/ || tags
    about: /about/ || user
  menu_settings:
    icons: true
    badges: true

  # ---------------------------------------------------------------
  # Sidebar Settings
  # ---------------------------------------------------------------
  sidebar:
    display: always
  avatar:
    url: avatar.png
    opacity: 0.8
    rounded: true
    rotated: true
  social:
    GitHub: https://github.com/liuyanjie || github
    E-Mail: liuyj619@gmail.com || envelope
  social_icons:
    enable: true
    icons_only: true
    transition: true
  # links:
  #   Title: http://example.com

  # ---------------------------------------------------------------
  # Footer Settings
  # See: https://theme-next.js.org/docs/theme-settings/footer
  # ---------------------------------------------------------------
  footer:
    since: 2018
    icon:
      name: heartbeat
      animated: true
      color: "#ff0000"
    copyright:
    powered: true
    beian:
      enable: false

  # ---------------------------------------------------------------
  # Post Settings
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  # Custom Page Settings
  # See: https://theme-next.js.org/docs/theme-settings/custom-pages
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  # Misc Theme Settings
  # See: https://theme-next.js.org/docs/theme-settings/miscellaneous
  # ---------------------------------------------------------------
  preconnect: true
  reading_progress:
    enable: true
  bookmark:
    enable: true
  github_banner:
    enable: true
    permalink: https://github.com/butonly
    title: Follow me on GitHub

  # ---------------------------------------------------------------
  # Font Settings
  # ---------------------------------------------------------------
  # Find fonts on Google Fonts (https://fonts.google.com)
  # All fonts set here will have the following styles:
  #   light | light italic | normal | normal italic | bold | bold italic
  # Be aware that setting too much fonts will cause site running slowly
  # ---------------------------------------------------------------
  # Web Safe fonts are recommended for `global` (and `title`):
  # Arial | Tahoma | Helvetica | Times New Roman | Courier New | Verdana | Georgia | Palatino | Garamond | Comic Sans MS | Trebuchet MS
  # ---------------------------------------------------------------
  font:
    enable: false

  # ---------------------------------------------------------------
  # SEO Settings
  # See: https://theme-next.js.org/docs/theme-settings/seo
  # ---------------------------------------------------------------
  index_with_subtitle: true
  exturl: false
  exturl_icon: true

  # ---------------------------------------------------------------
  # Third Party Plugins & Services Settings
  # See: https://theme-next.js.org/docs/third-party-services/
  # More plugins: https://github.com/next-theme/awesome-next
  # You may need to install the corresponding dependency packages
  # ---------------------------------------------------------------
  fancybox: true
  lazyload: true
  pangu: true

  # ---------------------------------------------------------------
  # Comments Settings
  # See: https://theme-next.js.org/docs/third-party-services/comments
  # ---------------------------------------------------------------
  disqus:
    enable: true
    shortname: liuyanjie
    count: true
    lazyload: true

  # ---------------------------------------------------------------
  # Post Widgets & Content Sharing Services
  # See: https://theme-next.js.org/docs/third-party-services/post-widgets
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  # Statistics and Analytics
  # See: https://theme-next.js.org/docs/third-party-services/statistics-and-analytics
  # ---------------------------------------------------------------
  google_analytics:
    tracking_id: 014348069229275019795:-z92dm0sjiy
    only_pageview: false
  baidu_analytics: 4cd57e104d0d9f5862dd91d0acdb9eee
  leancloud_visitors:
    enable: false
    app_id: yMJOxcMESfcKPsRm4QDdQuHB-gzGzoHsz
    app_key: qptX398Lv6Lujt1QSSlDA78B
  firestore:
    enable: false
    collection: articles
    apiKey: AIzaSyDgS8GXPvVxTQ_R2PPMJB3GYmC5fEGFkeI
    projectId: blog-25ee2
    bluebird: false

  # ---------------------------------------------------------------
  # Search Services
  # See: https://theme-next.js.org/docs/third-party-services/search-services
  # ---------------------------------------------------------------
  algolia_search:
    enable: true
  local_search:
    enable: false

  # ---------------------------------------------------------------
  # Chat Services
  # See: https://theme-next.js.org/docs/third-party-services/chat-services
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  # Tags Settings
  # See: https://theme-next.js.org/docs/tag-plugins/
  # ---------------------------------------------------------------
  tabs:
    transition:
      tabs: true
      labels: true
  pdf:
    enable: true
    height: 500px
  mermaid:
    enable: true
    theme: forest

  # ---------------------------------------------------------------
  # Animation Settings
  # ---------------------------------------------------------------
  nprogress:
    enable: true
    spinner: true
  canvas_ribbon:
    enable: true
